apiVersion: v1
entries:
  sd-on-eks:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-11-08T08:34:06.406058903Z"
    description: Stable Diffusion on EKS
    digest: 5d2cf4fb20d7f0f71eefa46754a7fe9ddcdac9630357dbed3ac0bea9198737fd
    name: sd-on-eks
    type: application
    urls:
    - https://aws-samples.github.io/stable-diffusion-on-eks/charts/sd-on-eks-0.1.0.tgz
    version: 0.1.0
generated: "2023-11-08T08:34:06.405243265Z"
